### PR TITLE
fix: vendeheydenMethod

### LINKED ISSUE #26: gMAM InexactError
the following code
```julia
using CriticalTransitions, Test

function meier_stein(u, p, t) # out-of-place
    x, y = u
    dx = x - x^3 - 10 * x * y^2
    dy = -(1 + x^2) * y
    [dx, dy]
end
σ = 0.25
sys = StochSystem(meier_stein, [], zeros(2), σ, idfunc, nothing, I(2), "WhiteGauss")

# initial path: parabola
xx = range(-1.0, 1.0, length = 30)
yy = 0.3 .* (-xx .^ 2 .+ 1)
init = Matrix([xx yy]')

method = CriticalTransitions.LBFGS()
gm = geometric_min_action_method(sys, init, maxiter = 100, method=method)
method = "HeymannVandenEijnden"
gm = geometric_min_action_method(sys, init, maxiter = 100, method=method)
```
gives
```
InexactError: Int64(4.384056944159697)
```

### PR DESCRIPTION
**Pull request by oameye**
resolves #26 

🎉

### CODE REVIEW

File: src/largedeviations/geometric_min_action_method.jl [hunk 1]
```diff
@@ -120,19 +118,30 @@ function heymann_vandeneijnden_step(
...
     lambdas, lambdas_prime = zeros(N), zeros(N)
-    x_prime = path_velocity(path, 0:dx:L; order=diff_order)
+    x_prime = path_velocity(path, range(0, L; length=N); order=diff_order)
 
     A = inv(covariance_matrix(sys))
 
     for i in 2:(N - 1)
-        lambdas[i] = anorm(drift(sys, path[:, i]), A) / anorm(path[:, i], A)
+        velocity_norm = anorm(x_prime[:, i], A)
+        if velocity_norm > 1e-14
```
Comment (reykboerner) [inline src/largedeviations/geometric_min_action_method.jl]: What is this if statement doing? Looks like it hardcodes stability?

**Review by reykboerner — COMMENTED** [review]
Awesome, thanks @oameye !
